[build]
  # Carpeta base del proyecto donde se encuentra package.json
  base = "app-drivique"

  # Comando para compilar el proyecto para la web
  command = "npm run build"

  # Directorio generado que contiene los archivos estáticos listos para subir (relativo a la carpeta base)
  publish = "dist"
