import { StyleSheet } from "react-native";

export const screen2Styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 24,
    alignItems: "center",
  },
  heroWrap: {
    width: "100%",
    marginBottom: 28,
  },
  mapCard: {
    width: "100%",
    height: 260,
    borderRadius: 20,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    position: "relative",
  },
  mapBg: {
    flex: 1,
    backgroundColor: "#E8F4F8",
    position: "relative",
  },
  streetH1: {
    position: "absolute",
    left: 0,
    right: 0,
    top: "40%",
    height: 8,
    backgroundColor: "#CBD5E1",
  },
  streetH2: {
    position: "absolute",
    left: 0,
    right: 0,
    top: "70%",
    height: 5,
    backgroundColor: "#CBD5E1",
  },
  streetV1: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: "35%",
    width: 8,
    backgroundColor: "#CBD5E1",
  },
  streetV2: {
    position: "absolute",
    top: 0,
    bottom: 0,
    right: "25%",
    width: 5,
    backgroundColor: "#CBD5E1",
  },
  pinWrap: {
    position: "absolute",
    top: 28,
    left: "33%",
  },
  pin: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "#1D4ED8",
    alignItems: "center",
    justifyContent: "center",
  },
  carDot: {
    position: "absolute",
  },
  reservaOverlay: {
    position: "absolute",
    bottom: 12,
    left: 12,
    right: 12,
    backgroundColor: "#FFFFFF",
    borderRadius: 14,
    padding: 14,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 8,
    elevation: 6,
  },
  reservaTitle: {
    fontSize: 14,
    fontWeight: "800",
    color: "#111827",
    marginBottom: 8,
  },
  reservaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 5,
  },
  reservaIcon: {
    fontSize: 14,
  },
  reservaText: {
    fontSize: 13,
    color: "#374151",
  },
  reservaBtn: {
    backgroundColor: "#1D4ED8",
    borderRadius: 8,
    paddingVertical: 8,
    alignItems: "center",
    marginTop: 8,
  },
  reservaBtnText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#fff",
  },
  textWrap: {
    alignItems: "center",
    paddingHorizontal: 8,
  },
  title: {
    fontSize: 28,
    fontWeight: "800",
    color: "#111827",
    textAlign: "center",
    marginBottom: 10,
  },
  subtitle: {
    fontSize: 15,
    color: "#6B7280",
    textAlign: "center",
    lineHeight: 23,
  },
});