import { Platform, StyleSheet } from "react-native";

const P = "#1D4ED8";

export const perfilStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#E9EDF8",
  },
  // Header
  header: {
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#F3F4F6",
    alignItems: "center",
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#111827",
  },
  // Card usuario
  userCard: {
    backgroundColor: "#FFFFFF",
    marginHorizontal: 16,
    marginTop: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  avatar: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: P,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarText: {
    fontSize: 20,
    fontWeight: "800",
    color: "#FFFFFF",
  },
  userInfo: { flex: 1 },
  userName: {
    fontSize: 16,
    fontWeight: "800",
    color: "#111827",
    marginBottom: 3,
  },
  userEmail: {
    fontSize: 12,
    color: "#6B7280",
  },
  btnEditar: {
    backgroundColor: "#EEF2FF",
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: P,
  },
  btnEditarText: {
    fontSize: 12,
    fontWeight: "700",
    color: P,
  },
  // Menú opciones
  menuSection: {
    backgroundColor: "#FFFFFF",
    marginHorizontal: 16,
    marginTop: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    overflow: "hidden",
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 16,
    gap: 14,
  },
  menuItemBorder: {
    borderBottomWidth: 1,
    borderBottomColor: "#F3F4F6",
  },
  menuIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 10,
    backgroundColor: "#EEF2FF",
    alignItems: "center",
    justifyContent: "center",
  },
  menuIcon: { fontSize: 18 },
  menuTextos: { flex: 1 },
  menuLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#111827",
  },
  menuSub: {
    fontSize: 12,
    color: "#9CA3AF",
    marginTop: 2,
  },
  menuArrow: {
    fontSize: 16,
    color: "#9CA3AF",
  },
  // Cerrar sesión
  cerrarSection: {
    backgroundColor: "#FFFFFF",
    marginHorizontal: 16,
    marginTop: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    overflow: "hidden",
  },
  cerrarBtn: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 16,
    gap: 14,
  },
  cerrarIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 10,
    backgroundColor: "#FEE2E2",
    alignItems: "center",
    justifyContent: "center",
  },
  cerrarLabel: {
    fontSize: 14,
    fontWeight: "700",
    color: "#DC2626",
  },
  // Eliminar cuenta
  eliminarWrap: {
    alignItems: "center",
    marginTop: 20,
    marginBottom: 8,
  },
  eliminarBtn: {
    paddingVertical: 8,
    paddingHorizontal: 16,
  },
  eliminarText: {
    fontSize: 13,
    color: "#DC2626",
    textDecorationLine: "underline",
  },
  // Pantalla editar
  editContainer: {
    flex: 1,
    backgroundColor: "#E9EDF8",
  },
  editHeader: {
    backgroundColor: "#FFFFFF",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#F3F4F6",
    gap: 12,
  },
  editHeaderBack: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    height: 36,
    paddingHorizontal: 14,
    borderRadius: 10,
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
  },
  editHeaderBackText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#1D4ED8",
  },
  editHeaderTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#111827",
  },
  editFormWrap: {
    marginHorizontal: 16,
    gap: 14,
  },
  editCampoWrap: { gap: 6 },
  editCampoLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: "#374151",
  },
  editInput: {
    backgroundColor: "#F9FAFB",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    paddingHorizontal: 14,
    paddingVertical: Platform.OS === "android" ? 10 : 13,
    fontSize: 14,
    color: "#111827",
  },
  editInputError: {
    borderColor: "#DC2626",
    backgroundColor: "#FEF2F2",
  },
  editErrorText: {
    fontSize: 12,
    color: "#DC2626",
  },
  editSelector: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#F9FAFB",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    paddingHorizontal: 14,
    paddingVertical: Platform.OS === "android" ? 10 : 13,
  },
  editSelectorText: { fontSize: 14 },
  editDropdown: {
    borderRadius: 10,
    borderWidth: 1,
    marginTop: 6,
    overflow: "hidden",
  },
  editDropdownItem: {
    paddingHorizontal: 14,
    paddingVertical: 11,
  },
  editDropdownText: { fontSize: 13.5, fontWeight: "600" },
  editFilaCelular: { flexDirection: "row", gap: 10 },
  editPrefijoBox: {
    borderWidth: 1.3,
    borderRadius: 10,
    paddingHorizontal: 12,
    justifyContent: "center",
    minWidth: 52,
    alignItems: "center",
  },
  editPrefijoText: { fontSize: 13, fontWeight: "700" },
  editInputCelular: { flex: 1 },
  editBtnGuardar: {
    backgroundColor: P,
    marginHorizontal: 16,
    marginTop: 24,
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: "center",
  },
  editBtnGuardarDisabled: {
    backgroundColor: "#93C5FD",
  },
  editBtnGuardarText: {
    fontSize: 15,
    fontWeight: "700",
    color: "#FFFFFF",
    letterSpacing: 0.5,
  },
});