import { StyleSheet, Dimensions } from 'react-native';

const { height } = Dimensions.get('window');

export const registroStyles = StyleSheet.create({
  flex: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
  },
  headerTitleContainer: { flex: 1 },
  headerTitleText: {
    fontSize: 22,
    fontWeight: "900",
    color: "#1E40AF",
    letterSpacing: -0.5,
  },
  guestBtn: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: "#1E40AF",
  },
  guestBtnTexto: {
    fontSize: 13,
    fontWeight: "700",
    color: "#1E40AF",
  },
  scrollContenedor: {
    flexGrow: 1,
    paddingBottom: 40,
  },
  header: {
    position: "relative",
    paddingHorizontal: 20,
    paddingTop: 32,
    paddingBottom: 20,
  },
  marcaTagline: {
    fontSize: 10,
    color: "#93A5D1",
    letterSpacing: 1.1,
    marginTop: 2,
    textTransform: "uppercase",
    textAlign: "center",
    marginBottom: 16,
  },
  cuerpo: {
    paddingHorizontal: 16,
    paddingTop: 32,
    paddingBottom: 24,
  },
  cardWrapper: {
    position: 'relative',
  },
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    paddingHorizontal: 24,
    paddingTop: 32,
    paddingBottom: 28,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 10,
  },
  encabezado: {
    alignItems: "center",
    marginBottom: 22,
  },
  titulo: {
    fontSize: 24,
    fontWeight: "800",
    color: "#111827",
    marginBottom: 6,
    textAlign: "center",
  },
  subtitulo: {
    fontSize: 14,
    color: "#6B7280",
    textAlign: "center",
    lineHeight: 20,
  },
  formulario: {
    gap: 0, 
  },
  acciones: {
    marginTop: 24, 
  },
  filaTerminosBox: {
    marginTop: 10,
    marginBottom: 10,
  },
  checkboxWrapper: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderWidth: 1.5,
    borderColor: '#D1D5DB',
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },
  checkboxActivo: {
    backgroundColor: '#1E40AF',
    borderColor: '#1E40AF',
  },
  textoTerminos: {
    fontSize: 13,
    lineHeight: 20,
  },
  enlaceTerminos: {
    color: '#1E40AF',
    fontWeight: '700',
    textDecorationLine: 'underline',
  },
  errorTerminos: {
    color: '#EF4444',
    fontSize: 12,
    marginTop: 4,
    marginBottom: 4,
  },
  loginRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 24,
  },
  loginTexto: {
    fontSize: 14,
  },
  loginLink: {
    fontSize: 14,
    fontWeight: '700',
  },

  // ── Modal de términos ────────────────────────────────────────
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  modalContenedor: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: height * 0.85,
    paddingBottom: 32,
  },
  modalHandle: {
    width: 40,
    height: 4,
    backgroundColor: '#D1D5DB',
    borderRadius: 2,
    alignSelf: 'center',
    marginTop: 12,
    marginBottom: 4,
  },
  modalEncabezado: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  modalTitulo: {
    fontSize: 17,
    fontWeight: '800',
    color: '#111827',
    flex: 1,
  },
  modalBotonCerrar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#F3F4F6',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 12,
  },
  modalBotonCerrarTexto: {
    fontSize: 16,
    color: '#6B7280',
    fontWeight: '700',
  },
  modalScroll: {
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 8,
  },
  modalSeccionTitulo: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1D4ED8',
    marginTop: 16,
    marginBottom: 6,
  },
  modalTexto: {
    fontSize: 13,
    color: '#374151',
    lineHeight: 22,
    marginBottom: 8,
  },
  modalFooterTexto: {
    fontSize: 13,
    color: '#6B7280',
    marginTop: 16,
    fontStyle: 'italic',
  },
  modalBotonesRow: {
    flexDirection: 'row',
    marginHorizontal: 24,
    marginTop: 16,
    gap: 12,
  },
  modalBotonCerrarSecundario: {
    flex: 1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    paddingVertical: 14,
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
  },
  modalBotonCerrarSecundarioTexto: {
    color: '#4B5563',
    fontSize: 15,
    fontWeight: '700',
  },
  modalBienvenidaOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  modalBienvenidaContenedor: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 24,
    width: '100%',
    alignItems: 'center',
  },
  modalBienvenidaTitulo: {
    fontSize: 15,
    textAlign: 'center',
    color: '#374151',
    marginBottom: 16,
    lineHeight: 22,
  },
  modalBienvenidaLista: {
    width: '100%',
  },
  modalBienvenidaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'transparent',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  modalBienvenidaItemIcono: {
    marginRight: 12,
  },
  modalBienvenidaItemTexto: {
    fontSize: 14,
    fontWeight: '600',
    color: '#111827',
  },
  modalBotonAceptarWrap: {
    flex: 2,
    borderRadius: 12,
  },
  modalBotonAceptar: {
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
  },
  modalBotonAceptarTexto: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
  },
});